In [ ]:
import numpy as np
import pandas as pd

In [ ]:
sales=pd.read_csv("sales_train_validation.csv")
calendar=pd.read_csv("calendar.csv")
prices=pd.read_csv("sell_prices.csv")

In [ ]:
sales.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,3,0,1,1,1,3,0,1,1
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,2,1,1,1,0,1,1,1
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,5,4,1,0,1,3,7,2
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,1,0,1,1,2,2,2,4

In [ ]:
sales.isnull().sum()

id          0
item_id     0
dept_id     0
cat_id      0
store_id    0
           ..
d_1909      0
d_1910      0
d_1911      0
d_1912      0
d_1913      0
Length: 1919, dtype: int64

In [ ]:
calendar.head()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1

In [ ]:
calendar.isnull().sum()

date               0
wm_yr_wk           0
weekday            0
wday               0
month              0
year               0
d                  0
event_name_1    1807
event_type_1    1807
event_name_2    1964
event_type_2    1964
snap_CA            0
snap_TX            0
snap_WI            0
dtype: int64

In [ ]:
prices.head()

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001   11325.0        9.58
1     CA_1  HOBBIES_1_001   11326.0        9.58
2     CA_1  HOBBIES_1_001   11327.0        8.26
3     CA_1  HOBBIES_1_001   11328.0        8.26
4     CA_1  HOBBIES_1_001   11329.0        8.26

In [ ]:
prices.isnull().sum()

store_id      0
item_id       1
wm_yr_wk      2
sell_price    2
dtype: int64

In [ ]:
days_col=[col for col in sales.columns if col.startswith("d_")]
days_col[:5]

['d_1', 'd_2', 'd_3', 'd_4', 'd_5']

In [ ]:
sales_long=pd.melt(sales,id_vars=["item_id","dept_id","cat_id",'store_id','state_id'],value_vars=days_col,var_name='d',value_name='sales')

In [ ]:
sales_long.head(20)

          item_id    dept_id   cat_id store_id state_id    d  sales
0   HOBBIES_1_001  HOBBIES_1  HOBBIES     CA_1       CA  d_1      0
1   HOBBIES_1_002  HOBBIES_1  HOBBIES     CA_1       CA  d_1      0
2   HOBBIES_1_003  HOBBIES_1  HOBBIES     CA_1       CA  d_1      0
3   HOBBIES_1_004  HOBBIES_1  HOBBIES     CA_1       CA  d_1      0
4   HOBBIES_1_005  HOBBIES_1  HOBBIES     CA_1       CA  d_1      0
5   HOBBIES_1_006  HOBBIES_1  HOBBIES     CA_1       CA  d_1      0
6   HOBBIES_1_007  HOBBIES_1  HOBBIES     CA_1       CA  d_1      0
7   HOBBIES_1_008  HOBBIES_1  HOBBIES     CA_1       CA  d_1     12
8   HOBBIES_1_009  HOBBIES_1  HOBBIES     CA_1       CA  d_1      2
9   HOBBIES_1_010  HOBBIES_1  HOBBIES     CA_1       CA  d_1      0
10  HOBBIES_1_011  HOBBIES_1  HOBBIES     CA_1       CA  d_1      0
11  HOBBIES_1_012  HOBBIES_1  HOBBIES     CA_1       CA  d_1      0
12  HOBBIES_1_013  HOBBIES_1  HOBBIES     CA_1       CA  d_1      0
13  HOBBIES_1_014  HOBBIES_1  HOBBIES     CA_1       CA  d_1      0
14  HOBBIES_1_015  HOBBIES_1  HOBBIES     CA_1       CA  d_1      4
15  HOBBIES_1_016  HOBBIES_1  HOBBIES     CA_1       CA  d_1      5
16  HOBBIES_1_017  HOBBIES_1  HOBBIES     CA_1       CA  d_1      0
17  HOBBIES_1_018  HOBBIES_1  HOBBIES     CA_1       CA  d_1      0
18  HOBBIES_1_019  HOBBIES_1  HOBBIES     CA_1       CA  d_1      0
19  HOBBIES_1_020  HOBBIES_1  HOBBIES     CA_1       CA  d_1      0